ssh:
  host: 172.17.0.1
  port: 22
  user: ubuntu
hooks:
  github:
    host: 0.0.0.0
    port: 8122
    path: /github/callback
    secret: chut
    repositories: ['repo']
  bitbucket:
    host: 0.0.0.0
    port: 8123
    path: /bitbucket/callback
    repositories: ['owner/repo']
compose:
  path: /path/to/docker-compose/

